apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.4.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: kubemart-operator.v0.0.70
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: App is the Schema for the apps API
        displayName: App
        kind: App
        name: apps.kubemart.civo.com
        version: v1alpha1
      - description: JobWatcher is the Schema for the jobwatchers API
        displayName: Job Watcher
        kind: JobWatcher
        name: jobwatchers.kubemart.civo.com
        version: v1alpha1
  description: kubemart-operator
  displayName: kubemart-operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - delete
                - get
                - list
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs/status
              verbs:
                - get
            - apiGroups:
                - kubemart.civo.com
              resources:
                - apps
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - kubemart.civo.com
              resources:
                - apps/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - kubemart.civo.com
              resources:
                - jobwatchers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - kubemart.civo.com
              resources:
                - jobwatchers/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: default
      deployments:
        - name: kubemart-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=10
                    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources: {}
                  - args:
                      - --metrics-addr=127.0.0.1:8080
                      - --enable-leader-election
                    command:
                      - /manager
                    image: docker.io/kubemart/kubemart-operator:v0.0.70
                    name: manager
                    resources:
                      limits:
                        cpu: 100m
                        memory: 30Mi
                      requests:
                        cpu: 100m
                        memory: 20Mi
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - configmaps/status
              verbs:
                - get
                - update
                - patch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: default
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - kubemart
  links:
    - name: Kubemart Operator
      url: https://kubemart-operator.domain
  maintainers:
    - email: zulh@civo.com
      name: Zulh
  maturity: alpha
  provider:
    name: Civo
    url: www.civo.com
  version: 0.0.70
  replaces: kubemart-operator.v0.0.69
