# permissions for end users to edit jobwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobwatcher-editor-role
rules:
  - apiGroups:
      - bizaar.civo.com
    resources:
      - jobwatchers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bizaar.civo.com
    resources:
      - jobwatchers/status
    verbs:
      - get
