# TODO - revise all permissions here
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bizaar-daemon-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
